using System.Linq;
using Utility.Serialization;
using Utility.Strings;

namespace Saber.Common.Platform
{
    public static class PageInfo
    {

        public static string[] GetRelativePath(string path)
        {
            var paths = path.Split('/');

            //translate root path to relative path
            if (paths[0] == "root")
            {
                if (paths.Length == 1) { return new string[] { "" }; }
                var newpath = paths.Skip(1).ToArray();
                switch (newpath[0].ToLower())
                {
                    case "css": newpath[0] = "/CSS"; break;
                    case "pages": newpath[0] = "/Pages"; break;
                    case "scripts": newpath[0] = "/Scripts"; break;
                    case "services": newpath[0] = "/Services"; break;
                    default:
                        //prevent hackers from snooping
                        return new string[] { };
                }
                return newpath;
            }
            else if (paths[0].ToLower() == "wwwroot")
            {
                paths[0] = "/wwwroot";
            }
            else if( paths[0].ToLower() == "content" && paths.Length > 1)
            {
                switch (paths[1].ToLower())
                {
                    case "partials":
                        paths[0] = "/Content";
                        break;
                    default:
                        paths[0] = "/Content/pages";
                        break;
                }
            }
            return paths;
        }

        public static string ConfigFilePath(string path)
        {
            var paths = GetRelativePath(path);
            var relpath = string.Join("/", paths);
            var file = paths[paths.Length - 1];
            var fileparts = file.Split(".", 2);
            return relpath.Replace(file, fileparts[0] + ".json");
        }

        public static Models.Page.Settings GetPageConfig(string path)
        {
            Server server = Server.Instance;
            var filename = ConfigFilePath(path);
            var config = (Models.Page.Settings)Serializer.ReadObject(server.LoadFileFromCache(filename, true), typeof(Models.Page.Settings));
            if (config != null) { return config; }

            //all else fails, generate a new page settings object
            var paths = GetRelativePath(path);
            var file = paths[paths.Length - 1];
            return new Models.Page.Settings()
            {
                title = new Models.Page.Title()
                {
                    prefix = "",
                    suffix = "",
                    body = file.Capitalize().Replace("-", " ").Replace("_", " "),
                    prefixId = 0,
                    suffixId = 0
                },
                description = "This page was generated by the Saber web development platform",
                security = new Models.Page.Security()
                {
                    read = new int[] { },
                    write = new int[] { },
                    secure = false
                }
            };
        }

        public static void SavePageConfig(string path, Models.Page.Settings config)
        {
            Server server = Server.Instance;
            var filename = ConfigFilePath(path);
            server.SaveFileFromCache(filename, Serializer.WriteObjectToString(config, Newtonsoft.Json.Formatting.Indented));
        }
    }
}
