CREATE TABLE [dbo].[Log_Errors]
(
	[logId] INT IDENTITY(1,1) PRIMARY KEY,
	[datecreated] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
    [userId] INT NOT NULL DEFAULT 0, 
    [url] VARCHAR(255) NOT NULL DEFAULT '', 
    [area] VARCHAR(255) NOT NULL DEFAULT '', 
    [message] VARCHAR(MAX) NOT NULL DEFAULT '', 
    [stacktrace] VARCHAR(MAX) NOT NULL DEFAULT '', 
    [data] NVARCHAR(MAX) NOT NULL DEFAULT ''
)
