CREATE TABLE [dbo].[Sessions]
(
	[Id] NVARCHAR(128) NOT NULL,
	[Value] NVARCHAR(MAX) NOT NULL,
	[Expires] DATETIME2(7) NOT NULL,
	CONSTRAINT [pk_Id] PRIMARY KEY CLUSTERED   
	( [Id] ASC ) 
	WITH (
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON
	) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]  
  
GO  
CREATE NONCLUSTERED INDEX [Index_Expires] ON [dbo].[Sessions] ( [Expires] ASC ) 
WITH (
	PAD_INDEX = OFF, 
	STATISTICS_NORECOMPUTE = OFF, 
	SORT_IN_TEMPDB = OFF, 
	DROP_EXISTING = OFF, 
	ONLINE = OFF, 
	ALLOW_ROW_LOCKS = ON, 
	ALLOW_PAGE_LOCKS = ON)  
GO  
