namespace Saber.Models
{
    public static class StaticFiles
    {
        public static KeyValuePair<string, string>[] MimeTypes = new KeyValuePair<string, string>[]
        {
            new KeyValuePair<string, string>(".acc", "audio/acc"),
            new KeyValuePair<string, string>(".avif", "image/avif"),
            new KeyValuePair<string, string>(".avi", "video/x-msvideo"),
            new KeyValuePair<string, string>(".bmp", "image/bmp"),
            new KeyValuePair<string, string>(".css", "text/css"),
            new KeyValuePair<string, string>(".csv", "text/csv"),
            new KeyValuePair<string, string>(".doc", "application/msword"),
            new KeyValuePair<string, string>(".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
            new KeyValuePair<string, string>(".eot", "application/vnd.ms-fontobject"),
            new KeyValuePair<string, string>(".epub", "application/epub+zip"),
            new KeyValuePair<string, string>(".gz", "application/gzip"),
            new KeyValuePair<string, string>(".gif", "image/gif"),
            new KeyValuePair<string, string>(".htm", "text/html"),
            new KeyValuePair<string, string>(".html", "text/html"),
            new KeyValuePair<string, string>(".ico", "image/vnd.microsoft.icon"),
            new KeyValuePair<string, string>(".ics", "text/calendar"),
            new KeyValuePair<string, string>(".jar", "application/java-archive"),
            new KeyValuePair<string, string>(".jpeg", "image/jpeg"),
            new KeyValuePair<string, string>(".jpg", "image/jpeg"),
            new KeyValuePair<string, string>(".js", "text/javascript"),
            new KeyValuePair<string, string>(".json", "application/json"),
            new KeyValuePair<string, string>(".jsonld", "application/ld+json"),
            new KeyValuePair<string, string>(".mid", "audio/midi"),
            new KeyValuePair<string, string>(".midi", "audio/midi"),
            new KeyValuePair<string, string>(".mjs", "text/javascript"),
            new KeyValuePair<string, string>(".mp3", "audio/mpeg"),
            new KeyValuePair<string, string>(".mp4", "video/mp4"),
            new KeyValuePair<string, string>(".mpeg", "video/mpeg"),
            new KeyValuePair<string, string>(".odp", "application/vnd.oasis.opendocument.presentation"),
            new KeyValuePair<string, string>(".ods", "application/vnd.oasis.opendocument.spreadsheet"),
            new KeyValuePair<string, string>(".odt", "application/vnd.oasis.opendocument.text"),
            new KeyValuePair<string, string>(".oga", "audio/ogg"),
            new KeyValuePair<string, string>(".ogv", "video/ogg"),
            new KeyValuePair<string, string>(".ogx", "application/ogg"),
            new KeyValuePair<string, string>(".opus", "audio/opus"),
            new KeyValuePair<string, string>(".otf", "font/otf"),
            new KeyValuePair<string, string>(".png", "image/png"),
            new KeyValuePair<string, string>(".pdf", "application/pdf"),
            new KeyValuePair<string, string>(".ppt", "application/vnd.ms-powerpoint"),
            new KeyValuePair<string, string>(".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
            new KeyValuePair<string, string>(".rar", "application/vnd.rar"),
            new KeyValuePair<string, string>(".rtf", "application/rtf"),
            new KeyValuePair<string, string>(".svg", "image/svg+xml"),
            new KeyValuePair<string, string>(".tar", "application/x-tar"),
            new KeyValuePair<string, string>(".tif", "image/tiff"),
            new KeyValuePair<string, string>(".tiff", "image/tiff"),
            new KeyValuePair<string, string>(".ts", "video/mp2t"),
            new KeyValuePair<string, string>(".ttf", "font/ttf"),
            new KeyValuePair<string, string>(".txt", "text/plain"),
            new KeyValuePair<string, string>(".vsd", "application/vnd.visio"),
            new KeyValuePair<string, string>(".wav", "audio/wav"),
            new KeyValuePair<string, string>(".weba", "audio/webm"),
            new KeyValuePair<string, string>(".webm", "video/webm"),
            new KeyValuePair<string, string>(".webp", "image/webp"),
            new KeyValuePair<string, string>(".woff", "font/woff"),
            new KeyValuePair<string, string>(".woff2", "font/woff2"),
            new KeyValuePair<string, string>(".xhtml", "application/xhtml+xml"),
            new KeyValuePair<string, string>(".xls", "application/vnd.ms-excel"),
            new KeyValuePair<string, string>(".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            new KeyValuePair<string, string>(".xml", "application/xml"),
            new KeyValuePair<string, string>(".xul", "application/vnd.mozilla.xul+xml"),
            new KeyValuePair<string, string>(".zip", "application/zip"),
            new KeyValuePair<string, string>(".3gp", "video/3gpp"),
            new KeyValuePair<string, string>(".3g2", "video/3gpp2"),
            new KeyValuePair<string, string>(".7z", "application/x-7z-compressed")
        };
    }
}
